### PR TITLE
fix: prefer input-based keyboard escape over app overlay

### LINKED ISSUE #135: Investigate issue with scrolling views
- Some views seem to require dragging close to the edge to get the screen to scroll.

### PR DESCRIPTION
**Pull request by telestrial**
This likely does not resolve [#135](https://github.com/SiaFoundation/sia-mobile/issues/135), as the deleted overlay in this PR was introduced after we had reports of scrolling issues. However, this was interfering with zoom functionality on `images/*` files and would probably confound any other scroll issue diagnosis.

### CODE REVIEW

**Comment by telestrial** [comment]
* **#146** <a href="https://app.graphite.dev/github/pr/SiaFoundation/sia-mobile/146?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#145** <a href="https://app.graphite.dev/github/pr/SiaFoundation/sia-mobile/145?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/SiaFoundation/sia-mobile/145?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#138** <a href="https://app.graphite.dev/github/pr/SiaFoundation/sia-mobile/138?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: src/screens/OnboardingScreen.tsx [hunk 1]
```diff
@@ -65,8 +72,11 @@ export default function OnboardingScreen() {
                 placeholder="eg: tiger harvest heart shine code feed monitor maple rug spend lemon trouble"
                 label="Recovery phrase"
                 {...newRecoveryPhraseInputProps}
-                height={100}
                 isMonospace
+                multiline
```
Comment (alexfreska) [inline src/screens/OnboardingScreen.tsx:76]: Should we make any similar changes to the read-only recovery phrase TextArea in the advanced settings screen?

**Review by alexfreska — APPROVED** [review]
Nice!! One comment.

File: src/screens/OnboardingScreen.tsx (hunk 1 above)
Comment (telestrial) [reply src/screens/OnboardingScreen.tsx:76]: Since it is not editable, the keyboard wouldn't be a factor. Right?

**Comment by telestrial** [comment]
### Merge activity

* **Oct 21, 7:17 PM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/SiaFoundation/sia-mobile/145).
* **Oct 21, 7:18 PM UTC**: [Graphite](https://app.graphite.dev/github/pr/SiaFoundation/sia-mobile/145) rebased this pull request as part of a merge.
* **Oct 21, 7:19 PM UTC**: @telestrial merged this pull request with [Graphite](https://app.graphite.dev/github/pr/SiaFoundation/sia-mobile/145).
